#ifndef COMPONENTDEFINITION_H_INCLUDED
#define COMPONENTDEFINITION_H_INCLUDED

#include <vector>
#include <unordered_map>
#include <boost/property_tree/ptree_fwd.hpp>
#include <Box2D/Collision/Shapes/b2PolygonShape.h>
#include "game/fwd.h"

namespace property
{
	class IPropertyObject;
}

namespace game
{
namespace spawn
{
	using vertex_cache_t = std::unordered_map<std::string, b2Vec2>;
	
	/// component definition.
	class Component
	{
	public:
		Component( const boost::property_tree::ptree& props );

		// data getters
		const std::string& type() const;
		float HP() const;
		float weight() const;

		const property::IPropertyObject& getProperties() const;

		std::shared_ptr<IComponent> create() const;
	private:
		std::string mType;
		float mHitPoints;
		float mWeight;
		std::shared_ptr<property::IPropertyObject> mProperties;
	};

	/// structure cell definition.
	class StructureCell
	{
	public:
		StructureCell(const boost::property_tree::ptree& props,
					  const vertex_cache_t& vertex_cache);

		long id() const;
		float maxLoad() const;
		const b2PolygonShape& shape() const;

		std::unique_ptr<IStructureCell> create() const;
	private:
		long mID;
		float mMaxLoad;
		b2PolygonShape mShape;
	};


	/// basic ship structure without function
	class Hull
	{
		typedef std::vector<StructureCell> cell_vec_t;
		struct Armour{ b2Vec2 p1; b2Vec2 p2; float hp; };
		typedef std::vector<Armour> armour_vec_t;
	public:
		Hull(const boost::property_tree::ptree& props);
		const cell_vec_t& cells() const;
		const armour_vec_t& armour() const;

		/// creates the (structural) part of the sub-structure of a ship.
		std::shared_ptr<ISubStructure> create() const;
	private:
		std::vector<StructureCell> mCells;
		std::vector<Armour> mArmour;
	};

	// ------------------------------------------------
	// additional data

	// ------------------------------------------------
	class Ship
	{
		struct cmpdef
		{
			std::string type;
			int cell;
		};
		typedef std::vector<cmpdef> cmp_vec_t;
	public:
		Ship(const boost::property_tree::ptree& props);

		const std::string& hull() const;
		const std::string& name() const;
		const cmp_vec_t& components() const;

		void addAttributes( property::IPropertyObject& obj ) const;
	private:
		std::string mHull;
		std::string mName;

		std::vector<cmpdef> mComponents;
		std::unordered_map<std::string, std::string> mAttributes;

		// attributes

	};

	// ------------------------------------------------------
	// projectile def
	// ------------------------------------------------------

	class Projectile
	{
	public:
		Projectile(const boost::property_tree::ptree& props);

		const std::string& name() const;
		float propellVelocity() const;
		float radius() const;
		float mass() const;
		int lifetime() const;
	private:
        std::string mName;
        float mPropellantVelocity; // velocity that is generated by the propellant
        float mRadius;
        float mMass;
        int mLifetime;
	};
}
}

#endif // COMPONENTDEFINITION_H_INCLUDED
