#ifndef SPROJECTILE_H_INCLUDED
#define SPROJECTILE_H_INCLUDED

#include <boost/property_tree/ptree_fwd.hpp>

namespace game
{
namespace spawn
{
	class SProjectile
	{
	public:
		SProjectile(const boost::property_tree::ptree& props);

		const std::string& name() const;
		float propellVelocity() const;
		float radius() const;
		float mass() const;
		int lifetime() const;
	private:
		std::string mName;
		float mPropellantVelocity; // velocity that is generated by the propellant
		float mRadius;
		float mMass;
		int mLifetime;
	};
}
}

#endif // SPROJECTILE_H_INCLUDED
